name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn build
      env:
        CI: true
    - uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: packages/frontend/dist/
    - uses: actions/upload-artifact@v2
      with:
        name: poller
        path: packages/poller/dist/
    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: packages/server/dist/
